import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import { NavigationBar } from "@/components/shared/Navbar";




const inter = Inter({
  weight:["400", "500", "600", "700" ,"800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>

          <NavigationBar />

          <main>
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
